=== Sancho-Pansa/Arkham-Helper/ArkhamCore/src/main/resources/Investigator.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Schema for Investigator JSON",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "expansion": {
        "type": "string",
        "enum": [
          "Ужас Аркхэма",
          "Ужас Данвича",
          "Ужас Иннсмута",
          "Ужас Кингспорта"
        ]
      },
      "location": {
        "type": "string"
      },
      "stamina": {
        "type": "integer"
      },
      "sanity": {
        "type": "integer"
      },
      "ability": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "phase": {
            "type": "string",
            "enum": [
              "ANY",
              "UPKEEP",
              "MOVEMENT",
              "ARKHAM_ENCOUNTER",
              "OTHER_WORLD_ENCOUNTER",
              "MYTHOS"
            ]
          }
        },
        "required": [
          "name",
          "description"
        ]
      },
      "possessions": {
        "type": "object",
        "properties": {
          "money": {
            "type": "integer"
          },
          "clues": {
            "type": "integer"
          },
          "commons": {
            "type": "object",
            "properties": {
              "random": {
                "type": "integer"
              },
              "fixed": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "random",
              "fixed"
            ]
          },
          "uniques": {
            "type": "object",
            "properties": {
              "random": {
                "type": "integer"
              },
              "fixed": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "random",
              "fixed"
            ]
          },
          "spells": {
            "type": "object",
            "properties": {
              "random": {
                "type": "integer"
              },
              "fixed": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "random",
              "fixed"
            ]
          },
          "skills": {
            "type": "object",
            "properties": {
              "random": {
                "type": "integer"
              },
              "fixed": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "random",
              "fixed"
            ]
          },
          "allies": {
            "type": "object",
            "properties": {
              "random": {
                "type": "integer"
              },
              "fixed": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "random",
              "fixed"
            ]
          }
        },
        "required": [
          "money",
          "clues"
        ]
      },
      "focus": {
        "type": "integer"
      },
      "minSpeed": {
        "type": "integer"
      },
      "maxSneak": {
        "type": "integer"
      },
      "minFight": {
        "type": "integer"
      },
      "maxWill": {
        "type": "integer"
      },
      "minLore": {
        "type": "integer"
      },
      "maxLuck": {
        "type": "integer"
      },
      "blessing": {
        "type": "integer",
        "enum": [-1, 0, 1]
      },
      "retainer": {
        "type": "boolean"
      },
      "cultist": {
        "type": "boolean"
      },
      "sheriff": {
        "type": "boolean"
      },
      "loan": {
        "type": "boolean"
      },
      "monsters": {
        "type": "number"
      },
      "gates": {
        "type": "number"
      },
      "story": {
        "type": "string"
      }
    },
    "required": [
      "name",
      "expansion",
      "location",
      "title",
      "stamina",
      "sanity",
      "ability",
      "possessions",
      "focus",
      "minSpeed",
      "maxSneak",
      "minFight",
      "maxWill",
      "minLore",
      "maxLuck"
    ]
  }
}

=== Sancho-Pansa/Arkham-Helper/ArkhamCore/src/main/resources/Investigators.json
[
  {
    "name": "Аманда Шарп",
    "title": "Студентка",
    "expansion": "Ужас Аркхэма",
    "stamina": 5,
    "sanity": 5,
    "minSpeed": 1,
    "maxSneak": 4,
    "minFight": 1,
    "maxWill": 4,
    "minLore": 1,
    "maxLuck": 4,
    "focus": 3,
    "ability": {
      "name": "Прилежная ученица",
      "description": "Всякий раз, когда Аманда берёт навыки из колоды, она тянет на одну карту больше положенного, а затем сбрасывает один из взятых навыков по своему выбору.",
      "phase": "ANY"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 1,
      "clues": 1,
      "common": {
        "random": 1,
        "fixed": []
      },
      "unique": {
        "random": 1,
        "fixed": []
      },
      "spell": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Банк Аркхэма"
  },
  {
    "name": "Боб Дженкинс",
    "title": "Коммивояжёр",
    "expansion": "Ужас Аркхэма",
    "stamina": 6,
    "sanity": 4,
    "minSpeed": 2,
    "maxSneak": 3,
    "minFight": 1,
    "maxWill": 6,
    "minLore": 0,
    "maxLuck": 4,
    "focus": 1,
    "ability": {
      "name": "Ловкий торгаш",
      "description": "Всякий раз, когда Боб берёт простые вещи из колоды, он тянет на одну карту больше положенного, а затем сбрасывает одну из взятых вещей по своему выбору.",
      "phase": "ANY"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 9,
      "clues": 0,
      "common": {
        "random": 2,
        "fixed": []
      },
      "unique": {
        "random": 2,
        "fixed": []
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Магазин"
  },
  {
    "name": "Винсент Ли",
    "title": "Доктор",
    "expansion": "Ужас Аркхэма",
    "stamina": 5,
    "sanity": 5,
    "minSpeed": 0,
    "maxSneak": 5,
    "minFight": 0,
    "maxWill": 4,
    "minLore": 2,
    "maxLuck": 4,
    "focus": 2,
    "ability": {
      "name": "Медик",
      "description": "Доктор Ли может восстановить себе или другому сыщику в одном месте с ним. При этом нельзя поднять здоровье сыщика выше предела.",
      "phase": "UPKEEP"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 9,
      "clues": 1,
      "common": {
        "random": 2,
        "fixed": []
      },
      "spell": {
        "random": 2,
        "fixed": []
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Больница Св. Марии"
  },
  {
    "name": "Глория Гольдберг",
    "title": "Писательница",
    "expansion": "Ужас Аркхэма",
    "stamina": 4,
    "sanity": 6,
    "minSpeed": 1,
    "maxSneak": 3,
    "minFight": 0,
    "maxWill": 5,
    "minLore": 1,
    "maxLuck": 5,
    "focus": 2,
    "ability": {
      "name": "Экстрасенсорная чувствительность",
      "description": "Когда Глория вступает в контакт в Ином мире, она тянет 2 подходящие по цвету карты врат и может выбрать для контакта любую из них.\nЭто свойство не работает в Аркхэме.",
      "phase": "OTHER_WORLD_ENCOUNTER"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 7,
      "clues": 2,
      "common": {
        "random": 2,
        "fixed": []
      },
      "spell": {
        "random": 2,
        "fixed": []
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Ресторанчик Вельмы"
  },
  {
    "name": "Даррел Симмонс",
    "title": "Фотограф",
    "expansion": "Ужас Аркхэма",
    "stamina": 4,
    "sanity": 6,
    "minSpeed": 2,
    "maxSneak": 3,
    "minFight": 2,
    "maxWill": 4,
    "minLore": 0,
    "maxLuck": 4,
    "focus": 2,
    "ability": {
      "name": "Стены помогают",
      "description": "Когда Даррел вступает в контакт в Аркхэме, он тянет 2 карты локаций и может выбрать для контакта любую из них.\nЭто свойство не работает в Иных мирах.",
      "phase": "ARKHAM_ENCOUNTER"
    },
    "blessing": 0,
    "retainer": true,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 4,
      "clues": 1,
      "common": {
        "random": 1,
        "fixed": []
      },
      "unique": {
        "random": 2,
        "fixed": []
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Офис газеты"
  },
  {
    "name": "Дженни Барнс",
    "title": "Дилетантка",
    "expansion": "Ужас Аркхэма",
    "stamina": 4,
    "sanity": 6,
    "minSpeed": 0,
    "maxSneak": 4,
    "minFight": 1,
    "maxWill": 5,
    "minLore": 1,
    "maxLuck": 5,
    "focus": 1,
    "ability": {
      "name": "Трастовый фонд",
      "description": "Дженни получает $1.",
      "phase": "UPKEEP"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 10,
      "clues": 0,
      "common": {
        "random": 2,
        "fixed": []
      },
      "unique": {
        "random": 1,
        "fixed": []
      },
      "spell": {
        "random": 1,
        "fixed": []
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Вокзал"
  },
  {
    "name": "Джо Даймонд",
    "title": "Частный детектив",
    "expansion": "Ужас Аркхэма",
    "stamina": 6,
    "sanity": 4,
    "minSpeed": 3,
    "maxSneak": 4,
    "minFight": 2,
    "maxWill": 3,
    "minLore": 0,
    "maxLuck": 3,
    "focus": 3,
    "ability": {
      "name": "Интуиция",
      "description": "Всякий раз, когда Джо тратит улику во время проверки навыка, он бросает ещё один дополнительный кубик.",
      "phase": "ANY"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 8,
      "clues": 3,
      "common": {
        "random": 2,
        "fixed": [
          "Пистолет 45-го калибра"
        ]
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Полицейский участок"
  },
  {
    "name": "Декстер Дрейк",
    "title": "Иллюзионист",
    "expansion": "Ужас Аркхэма",
    "stamina": 5,
    "sanity": 5,
    "minSpeed": 3,
    "maxSneak": 4,
    "minFight": 2,
    "maxWill": 3,
    "minLore": 0,
    "maxLuck": 3,
    "focus": 3,
    "ability": {
      "name": "Магический дар",
      "description": "Всякий раз, когда Декстер берет заклинания из колоды, он тянет на одну карту больше положенного и потом сбрасывает одно из взятых заклинаний по выбору.",
      "phase": "ANY"
    },
    "blessing": 0,
    "retainer": false,
    "loan": false,
    "cultist": false,
    "sheriff": false,
    "possessions": {
      "money": 5,
      "clues": 0,
      "common": {
        "random": 1,
        "fixed": []
      },
      "unique": {
        "random": 1,
        "fixed": []
      },
      "spell": {
        "random": 2,
        "fixed": ["Иссушение"]
      },
      "skill": {
        "random": 1,
        "fixed": []
      }
    },
    "location": "Старинная лавка волшбы"
  }
]
